### ISSUE TITLE
daisyduck can't find libduck

### ISSUE THREAD

**Issue by shadow-absorber** [Skywalker13/DaisyDuck#10]
no matter what environment variables shadow sets after using `./configure` and `make` for both daisyduck and libduck the executable daisyduck can't find libduck

**Comment by Skywalker13** [comment]
It's not a DaisyDuck issue. It's just a question of dynamic linking and program loader on Linux systems. Install properly the libraries and everything will just work.

First, check with `ldd` how is linked daisyduck.

By default the configure script uses `/usr/local` as prefix, the shared objects are saved in `/usr/local/lib` after `make install`.

![image](https://github.com/user-attachments/assets/cb803ecb-d4af-47c1-8fbf-5cbd64719a0f)

You can use an other prefix if you want. `./configure --prefix=/usr` when compiling libduck and daisyduck.

You can try to refresh the ld bindings of your system with `sudo ldconfig`.
You can check if `ld` looks for the `/usr/local/lib` directory in its config `/etc/ld.so.conf`.

An other way, just build libduck only in static with
```
./configure --disable-shared --enable-static
make
make install
```
So, when daisyduck is linked, it will use only the static lib of libduck instead of the dynamic. Of course you must remove the previous version `make uninstall`

etc.

**Comment by shadow-absorber** [comment]
thanks this helped shadow figure out that they needed to use ldconfig to get the path added to load the lib
